cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers
    - $HOME/.sbt
    - $HOME/.cache
    - $HOME/.cache/coursier

language: scala
scala:
  - 2.13.2
jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: "gastonschabas"

if: branch = master

script:
  - sbt ++$TRAVIS_SCALA_VERSION scalafmtCheckAll
  - sbt ++$TRAVIS_SCALA_VERSION scalafmtSbtCheck
  - sbt ++$TRAVIS_SCALA_VERSION scalafmtSbtCheck
  - sbt ++$TRAVIS_SCALA_VERSION scapegoat
  - sbt ++$TRAVIS_SCALA_VERSION coverage test
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport
  - sonar-scanner
