cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers
    - $HOME/.cache/coursier/v1

language: scala
scala:
  - 2.12.11
  - 2.11.12
  - 2.13.2
jdk:
  - openjdk8

script:
  - sbt "++$TRAVIS_SCALA_VERSION!" test
