cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers
    - $HOME/.cache/coursier/v1

language: scala
scala:
  - 2.13.2
jdk:
  - openjdk11

if: branch = master

addons:
  sonarcloud:
    organization: "gastonschabas" # the key of the org you chose at step #3

script:
  - sbt ++$TRAVIS_SCALA_VERSION ";scalafmtCheckAll ;scalafmtSbtCheck ;scalafmtSbtCheck ;scapegoat ;coverage test ;coverageReport"
  - sonar-scanner
