addSbtPlugin("org.scalameta"     %% "sbt-scalafmt"          % "2.4.4")
addSbtPlugin("org.scalastyle"    %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("org.scoverage"     %% "sbt-scoverage"         % "1.9.2")
addSbtPlugin("com.github.mwz"    %% "sbt-sonar"             % "2.2.0")
addSbtPlugin("com.typesafe.play" %% "sbt-plugin"            % "2.8.11")
addSbtPlugin("com.github.sbt"     % "sbt-native-packager"   % "1.9.7")
addSbtPlugin("org.wartremover"    % "sbt-wartremover"       % "2.4.16")
addSbtPlugin("org.scala-sbt"      % "sbt-autoversion"       % "1.0.0")
