addSbtPlugin("org.scalameta"          %% "sbt-scalafmt"          % "2.4.0")
addSbtPlugin("com.sksamuel.scapegoat" %% "sbt-scapegoat"         % "1.1.0")
addSbtPlugin("org.scalastyle"         %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("org.scoverage"          %% "sbt-scoverage"         % "1.6.1")
addSbtPlugin("org.scoverage"          %% "sbt-coveralls"         % "1.2.7")
addSbtPlugin("com.github.mwz"         %% "sbt-sonar"             % "2.1.1")
