name: CI - concurrent jobs
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actual Branch
        uses: actions/checkout@v2
      - name: Setup Java Environment
        uses: actions/setup-java@v1.3.0
        with:
          java-version: '1.8'
      - name: Cache Sbt Paths
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Compile
        run: sbt compile
      - name: Check Scala Format
        run: sbt scalafmtCheckAll
      - name: Check Sbt Format
        run: sbt scalafmtSbtCheck
      - name: Run Static Code Analyzer
        run: sbt scapegoat
      - name: Test With Coverage
        run: |
          sbt coverage test
          sbt coverageReport
      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sbt -Dsonar.organization=gastonschabas -Dsonar.projectKey=gastonschabas_rumble-on-scala -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN sonarScan
