name: CI
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v5
      - name: Compile
        run: sbt compile
      - name: Check Scala Format
        run: sbt scalafmtCheckAll
      - name: Check Sbt Format
        run: sbt scalafmtSbtCheck
