name: CI
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actual Branch
        uses: actions/checkout@v2
      - name: Setup Java Environment
        uses: actions/setup-java@v1.3.0
        with:
          java-version: '1.8'
      - name: Cache Sbt Paths
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Compile -> Check Format -> Lint -> Unit Test
        run: sbt ;compile;scalafmtCheckAll;scalafmtSbtCheck;scapegoat;test
