name: Continious Integration
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.yml'
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache SBT
      uses: actions/cache@v2
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
    - uses: olafurpg/setup-scala@v5
    - name: Compile
      run: sbt compile

  check-format:
    runs-on: ubuntu-latest
    needs: compile
    steps:
    - name: Check Scala Format
      run: sbt scalafmtCheckAll
    - name: Check Sbt Format
      run: sbt scalafmtSbtCheck

  unit-test:
    runs-on: ubuntu-latest
    needs: compile
    steps:
    - name: Unit Test
      run: sbt test

  scapegoat:
    runs-on: ubuntu-latest
    needs: compile
    steps:
    - name: Scapegoat
      run: sbt scapegoat

  scalastyle:
    runs-on: ubuntu-latest
    needs: compile
    steps:
    - name: Scala Style
      run: sbt scalastyle

  sonar-cloud:
    runs-on: ubuntu-latest
    needs: [unit-test, scapegoat, scalastyle]
    steps:
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
