name: Continious Integration
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.yml'
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Cache SBT
      uses: actions/cache@v2
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
    - name: Setup Scala
      uses: actions/setup-java@v1
      with:
        java-version: 11
    # - name: Compile
    #   run: sbt compile
    # - name: Check Scala Format
    #   run: sbt scalafmtCheckAll
    # - name: Check Sbt Format
    #   run: sbt scalafmtSbtCheck
    # - name: Unit Test with Coverage
    #   env:
    #     COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    #   run: |
    #     sbt coverage test
    #     sbt coverageReport coveralls
    # - name: Scapegoat
    #   run: sbt scapegoat
    # - name: Scala Style
    #   run: sbt scalastyle
    - name: Sonar Scala
      run: |
        sbt \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.organization=gastonschabas \
        -Dsonar.projectKey=gastonschabas_rumble-on-scala \
        -Dsonar.sources=src/main/scala \
        -Dsonar.tests=src/test/scala \
        -Dsonar.scala.scalastyle.reportPaths=target/scalastyle-result.xml \
        -Dsonar.scala.scapegoat.reportPaths=target/scala-2.13/scapegoat-report/scapegoat-scalastyle.xml \
        -Dsonar.scala.coverage.reportPaths=target/scala-2.13/scoverage-report/scoverage.xml \
        -Dsonar.login=${{ secrets.SONAR_TOKEN }} clean coverage test coverageReport scapegoat scalastyle sonarScan
