name: CI
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actual Branch
        uses: actions/checkout@v2
      - name: Setup Java Environment
        uses: actions/setup-java@v1.3.0
        with:
          java-version: '1.8'
      - name: Cache Sbt Paths
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Compile
        run: sbt compile
  scala-format:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check Scala Format
        run: sbt ";scalafmtCheckAll"
  scala-sbt-format:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check Sbt Format
        run: sbt ";scalafmtSbtCheck"
  scapegoat:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run Static Code Analyzer
        run: sbt ";scapegoat"
  scala-unit-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test
        run: sbt ";test"
