name: Continious Integration
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.yml'
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v5
      - name: Compile
        run: sbt compile

  check-format:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Check Scala Format
        run: sbt scalafmtCheckAll
      - name: Check Sbt Format
        run: sbt scalafmtSbtCheck

  unit-test:
    needs: compile
    steps:
      - name: Unit Test
        run: sbt test

  scapegoat:
    needs: compile
    steps:
      - name: Scapegoat
        run: sbt scapegoat

  scalastyle:
    needs: compile
    steps:
      - name: Scala Style
        run: sbt scalastyle

  sonar-cloud:
    needs: [unit-test, scapegoat, scalastyle]
      steps:
       - name: SonarCloud Scan
       uses: sonarsource/sonarcloud-github-action@master
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
