name: Continious Integration
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.yml'
jobs:
  environment-setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Cache SBT
      uses: actions/cache@v2
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
    - name: Setup Scala
      uses: actions/setup-java@v1
      with:
        java-version: 11
  compile:
    - runs-on: ubuntu-latest
    - needs: environment-setup
    - name: Compile
      run: sbt compile
  code-format:
    - runs-on: ubuntu-latest
    - needs: environment-setup
    - name: Check Scala Format
      run: |
        sbt \
          scalafmtCheckAll \
          scalafmtSbtCheck
  static-code-analyzer:
    - runs-on: ubuntu-latest
    - needs: environment-setup
    - name: Static Code Analyser
      run: sbt scapegoat
  test-with-coverage:
    - runs-on: ubuntu-latest
    - needs: compile
    - name: Unit Test with Coverage
      run: |
        sbt coverage test coverageReport
  sonar:
    - runs-on: ubuntu-latest
    - needs: [code-format, static-code-analyzer, test-with-coverage]
    - name: Sonar
      run: |
        sbt \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.organization=gastonschabas \
        -Dsonar.projectKey=gastonschabas_rumble-on-scala \
        -Dsonar.sources=src/main/scala \
        -Dsonar.tests=src/test/scala \
        -Dsonar.scala.scalastyle.reportPaths=target/scalastyle-result.xml \
        -Dsonar.scala.scapegoat.reportPaths=target/scala-2.13/scapegoat-report/scapegoat-scalastyle.xml \
        -Dsonar.scala.coverage.reportPaths=target/scala-2.13/scoverage-report/scoverage.xml \
        -Dsonar.login=${{ secrets.SONAR_TOKEN }} sonarScan
