name: Set any open PR as Draft
on:
  workflow_dispatch:
jobs:
  set-as-draft:
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: |
          for base_pr_id in $(gh pr list --state "open" --json number --jq '.[].number'); do 
            gh pr ready $base_pr_id --undo
          done
